# Generated by Django 4.0.4 on 2022-05-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltasks',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_name',
            new_name='name',
        ),
    ]
